import { Provider } from "@/components/ui/provider";
import { Box, Heading } from "@chakra-ui/react";
import type { Metadata } from "next";
import "../globals.css";
import Header from "./components/Header";
import NavLinks from "./components/NavLinks";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DashboardLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <Provider>
      <Box width={"15%"} p={5} bg={"primary.base"}>
        <Heading fontSize={30}>Ca$hTrack</Heading>

        <Box mt={5}>
          <NavLinks />
        </Box>
      </Box>
      <Box width={"85%"} mt={"4rem"}>
        <Header />
        {children}
      </Box>
    </Provider>
  );
};

export default DashboardLayout;
